apiVersion: v1
kind: Service
metadata:
  name: acme-challenge
  namespace: istio-system
  labels:
    app: acme-challenge
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: acme-challenge
---
apiVersion: v1
kind: Pod
metadata:
  name: acme-challenge
  namespace: istio-system
  labels:
    app: acme-challenge
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: acme-challenge
  namespace: istio-system
  labels:
    app: acme-challenge
spec:
  hosts:
    - staging.{{ .Values.app.host }}
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
      - uri:
          regex: .*\/.well-known\/acme-challenge\/.*
      route:
        - destination:
            host: acme-challenge
            port:
              number: 80