apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-tls
  namespace: istio-system
spec:
  secretName: {{ .Values.app.name }}-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  issuerRef:
    name: {{ .Values.tls.certManagerClusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.app.host }}
  dnsNames:
    - {{ .Values.app.host }}
