apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-staging-tls
  namespace: istio-system
spec:
  secretName: {{ .Values.app.name }}-staging-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
{{/*  commonName: {{ .Values.app.host }}*/}}
  dnsNames:
    - staging.{{ .Values.app.host }}
