{{- range $key, $val := .Values.environment }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $val.certificate.name }}
  namespace: istio-system
spec:
  secretName: {{ $val.certificate.name }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  issuerRef:
    name: {{ $val.certificate.issuerRef }}
    kind: ClusterIssuer
  commonName: {{ $val.certificate.commonName }}
  dnsNames:
    - {{- if ne $key "prod" -}}{{ $key }}.{{- end -}}{{ $val.certificate.commonName }}
---
{{- end }}