apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-cert
  namespace: istio-system
spec:
  secretName: {{ .Values.app.name }}-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "www.{{ .Values.app.domain }}"
    - "{{ .Values.app.domain }}"
    - "staging-api.{{ .Values.app.domain }}"
    - "prod-api.{{ .Values.app.domain }}"
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io