{{- range $key, $val := .Values.environment }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ $val.clusterIssuer.name }}
  namespace: istio-system
spec:
  acme:
    email: your-email@{{ .Values.app.host }}
    server: {{ $val.clusterIssuer.server }}
    privateKeySecretRef:
      name: {{ $val.clusterIssuer.privateKeySecretRef }}
    solvers:
      - http01:
          ingress:
            ingressClassName: istio
        selector: {}
---
{{- end }}