app:
  name: "mucha-backend"
  host:

environment:
  staging:
    clusterIssuer:
      name: letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef: letsencrypt-staging
    certificate:
      issuerRef:
        name: letsencrypt-staging
        kind: ClusterIssuer

