apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
#        - "{{ .Values.environment.domain }}"
#      tls:
#        # Optional: Add TLS configuration if needed
#        mode: PASSTHROUGH
