apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tls-gateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "{{ .Values.app.name }}-cert"
    oci.oraclecloud.com/oci-network-security-groups: "{{ .Values.oci.networkSecurityGroup }}"
    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"
    oci.oraclecloud.com/security-rule-management-mode: "None"
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: {{ .Values.app.domain }}-http
      hostname: "*.{{ .Values.app.domain }}"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: {{ .Values.app.domain }}-https
      hostname: "{{ .Values.app.domain }}"
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          name: {{ .Values.app.name }}-cert
          namespace: istio-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment.name }}-0
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment.name }}
spec:
  parentRefs:
    - name: tls-gateway
      namespace: istio-system
  rules:
  - backendRefs:
    - name: {{ .Values.app.name }}
      port: {{ .Values.environment.containerPort }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment.name }}-1
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment.name }}
spec:
  parentRefs:
    - name: tls-gateway
      namespace: istio-system
  hostnames:
    - {{ .Values.environment.domain }}
  rules:
  - backendRefs:
    - name: {{ .Values.app.name }}
      port: {{ .Values.environment.containerPort }}