apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: "{{ .Values.app.name }}-{{ .Values.deployment.environment }}-tls"
    {{/*    oci.oraclecloud.com/oci-network-security-groups: "{{ .Values.oci.networkSecurityGroup }}"*/}}
    {{/*    service.beta.kubernetes.io/oci-load-balancer-security-list-management-mode: "None"*/}}
    {{/*    oci.oraclecloud.com/security-rule-management-mode: "None"*/}}
spec:
  selector:
    istio: ingress
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
{{/*        - {{ .Values.app.host }}*/}}
{{/*    - port:*/}}
{{/*        number: 80*/}}
{{/*        name: staging-http*/}}
{{/*        protocol: HTTP*/}}
{{/*      hosts:*/}}
{{/*        - staging.{{ .Values.app.host }}*/}}
{{/*    - port:*/}}
{{/*        number: 443*/}}
{{/*        name: https*/}}
{{/*        protocol: HTTPS*/}}
{{/*      tls:*/}}
{{/*        mode: SIMPLE*/}}
{{/*        credentialName: {{ .Values.app.name }}-prod-tls*/}}
{{/*        namespace:*/}}
{{/*      hosts:*/}}
{{/*        - {{ .Values.app.host }}*/}}
    - port:
        number: 443
        name: staging-https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.app.name }}-staging-tls
        namespace: istio-system
      hosts:
        - staging.{{ .Values.app.host }}
