apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.deployment.environment }}
    version: {{ .Values.deployment.version }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: {{ .Values.app.port }}
    - protocol: TCP
      name: https
      port: 443
      targetPort: {{ .Values.app.port }}
