apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.environment.port }}
      targetPort: {{ .Values.environment.targetPort }}
      name: http
