apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    environment: {{ .Values.environment.name }}

spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: {{ .Values.environment.port }}
      targetPort: {{ .Values.environment.targetPort }}
      protocol: TCP
      name: http
