{{/*apiVersion: networking.istio.io/v1alpha3*/}}
{{/*kind: VirtualService*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Release.Name }}-{{ .Values.environment.name }}-virtualservice*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*  labels:*/}}
{{/*    app: {{ .Values.app.name }}*/}}
{{/*    environment: {{ .Values.environment.name }}*/}}
{{/*spec:*/}}
{{/*  hosts:*/}}
{{/*    - "*"*/}}
{{/*    - "{{ .Values.environment.domain }}"*/}}
{{/*  gateways:*/}}
{{/*    - istio-gateway.istio-system.svc.cluster.local*/}}
{{/*  http:*/}}
{{/*    - match:*/}}
{{/*        - uri:*/}}
{{/*            prefix: "{{ .Values.environment.path }}"*/}}
{{/*      route:*/}}
{{/*        - destination:*/}}
{{/*            host: {{ .Values.app.name }}*/}}
{{/*            port:*/}}
{{/*              number: {{ .Values.environment.port }}*/}}
