apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - "*"
#    - "{{ .Values.environment.domain }}"
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - match:
        - uri:
            prefix: "{{ .Values.environment.path }}"
      route:
        - destination:
            host: {{ .Values.app.name }}
            port:
              number: {{ .Values.environment.port }}
