# Global settings for Istio
#global:
#  istio:
#    ingressGateway: "istio-ingressgateway"

# Application settings - Define the app name and version
app:
  name: "mucha-backend"    # Application name
  domain: "mucha.com.mp"

# Environment-specific configurations
environment:
  name: ""
  domain: ""
  path: "/"
  image: ""
  replicas: 3
  httpPort: 80
  httpsPort: 443
  httpTargetPort: 80
  httpsTargetPort: 443
  httpContainerPort: 80
  httpsContainerPort: 443
  nodePort: 31600
  version: ""

oci:
  networkSecurityGroup: ""