# Global settings for Istio
global:
  istio:
    ingressGateway: "istio-ingressgateway"

# Application settings - Define the app name and version
app:
  name: "mucha-backend"    # Application name

# Environment-specific configurations
environment:
  name: ""
  domain: "mucha.com.mp"
  path: "/"
  image: "my-app"
  replicas: 3
  port: 80
  targetPort: 80
  containerPort: 80
  nodePort: 31600
  version: ""