global:
  istio:
    ingressGateway: istio-ingressgateway
app:
  name: mucha-backend
  version: v1
environment:
  name: staging
  domain: staging.api.mucha.com.mp
  path: /
  image: mrmineleung/mucha-backend
  replicas: 3
  port: 80
  targetPort: 80
  containerPort: 80
  version: 20250616-044106
