apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-pvc
  namespace: caddy-server
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
