apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mucha-backend-pvc
spec:
  storageClassName: "oci-bv"
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
