apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-pvc
  namespace: caddy
spec:
  storageClassName: "oci-bv"
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
