apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mucha-staging-pvc
  namespace: mucha-staging
spec:
  storageClassName: "oci-bv"
  volumeMode: Block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
