apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app.name }}-prod-tls
  namespace: istio-ingress
spec:
  secretName: {{ .Values.app.name }}-prod-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - server auth
    - client auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.app.host }}
